# Generated by Django 2.2.7 on 2019-11-19 23:16

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(blank=True, max_length=10, validators=[django.core.validators.RegexValidator('^[0-9]{9}')])),
                ('is_student', models.BooleanField(default=True)),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProfilePic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pic1', models.ImageField(upload_to='profile_pics')),
                ('pic2', models.ImageField(blank=True, upload_to='profile_pics')),
                ('pic3', models.ImageField(blank=True, upload_to='profile_pics')),
                ('pic4', models.ImageField(blank=True, upload_to='profile_pics')),
                ('pic5', models.ImageField(blank=True, upload_to='profile_pics')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_pic', to='papyri.UserInfo')),
            ],
        ),
    ]
