# Generated by Django 2.2.7 on 2019-11-14 05:13

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfilePics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pic1', models.ImageField(upload_to='profile_pics')),
                ('pic2', models.ImageField(upload_to='profile_pics')),
                ('pic3', models.ImageField(upload_to='profile_pics')),
                ('pic4', models.ImageField(upload_to='profile_pics')),
                ('pic5', models.ImageField(upload_to='profile_pics')),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('uid', models.PositiveIntegerField(primary_key=True, serialize=False, validators=[django.core.validators.MaxLengthValidator(9), django.core.validators.MinLengthValidator(9)])),
                ('is_student', models.BooleanField(default=True)),
                ('profile_pics', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='papyri.ProfilePics')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
