# Generated by Django 2.2.7 on 2019-11-14 05:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('papyri', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfilePic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pic1', models.ImageField(upload_to='profile_pics')),
                ('pic2', models.ImageField(blank=True, upload_to='profile_pics')),
                ('pic3', models.ImageField(blank=True, upload_to='profile_pics')),
                ('pic4', models.ImageField(blank=True, upload_to='profile_pics')),
                ('pic5', models.ImageField(blank=True, upload_to='profile_pics')),
            ],
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='profile_pics',
        ),
        migrations.DeleteModel(
            name='ProfilePics',
        ),
        migrations.AddField(
            model_name='profilepic',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_pic', to='papyri.UserInfo'),
        ),
    ]
