# Generated by Django 2.2.7 on 2019-11-30 08:45

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('papyri', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('term', models.CharField(max_length=200)),
                ('year', models.CharField(max_length=10)),
                ('registration_code', models.CharField(max_length=5)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Lecture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slide_link', models.URLField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('in_session', models.BooleanField(default=True)),
                ('c', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='papyri.ClassInfo')),
            ],
        ),
        migrations.AlterField(
            model_name='profilepic',
            name='pic1',
            field=models.ImageField(blank=True, upload_to='profile_pics'),
        ),
        migrations.CreateModel(
            name='StudentClassRelationship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='papyri.ClassInfo')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('question', models.CharField(max_length=2000)),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(default=False)),
                ('released', models.BooleanField(default=False)),
                ('score', models.PositiveIntegerField(default=0)),
                ('answer_0', models.CharField(max_length=200)),
                ('answer_1', models.CharField(max_length=200)),
                ('answer_2', models.CharField(max_length=200)),
                ('answer_3', models.CharField(max_length=200)),
                ('correct_answer', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(3, message='Only accepts values from 0 to 3')])),
                ('class_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='papyri.ClassInfo')),
            ],
        ),
        migrations.CreateModel(
            name='LectureAttendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lecture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='papyri.Lecture')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
