# Generated by Django 2.2.7 on 2019-11-21 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papyri', '0002_classinfo_lecture_lectureattendance_quiz_quizquestion_userclassrelationship'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilepic',
            name='pic1',
            field=models.ImageField(blank=True, upload_to='profile_pics'),
        ),
    ]
