# Generated by Django 2.2.7 on 2019-11-22 02:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('papyri', '0003_auto_20191120_1747'),
        ('papyri', '0003_auto_20191121_0151'),
    ]

    operations = [
    ]
