# Generated by Django 2.2.7 on 2019-11-21 16:49

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('papyri', '0003_auto_20191121_0151'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserClassRelationship',
            new_name='StudentClassRelationship',
        ),
        migrations.RenameField(
            model_name='studentclassrelationship',
            old_name='user_id',
            new_name='student_id',
        ),
    ]
