# Generated by Django 2.2.7 on 2019-11-22 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('papyri', '0004_auto_20191121_1649'),
    ]

    operations = [
        migrations.RenameField(
            model_name='classinfo',
            old_name='teacher_id',
            new_name='teacher',
        ),
    ]
