# Generated by Django 2.2.7 on 2019-11-23 00:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('papyri', '0005_auto_20191122_1917'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentclassrelationship',
            old_name='class_id',
            new_name='c',
        ),
        migrations.RenameField(
            model_name='studentclassrelationship',
            old_name='student_id',
            new_name='student',
        ),
    ]
