# Generated by Django 2.2.7 on 2019-12-02 01:51

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('papyri', '0006_auto_20191202_0144'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='score',
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correct_answer', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(3, message='Only accepts values from 0 to 3')])),
                ('num_students', models.PositiveIntegerField()),
                ('choice_0_percent', models.FloatField()),
                ('choice_1_percent', models.FloatField()),
                ('choice_2_percent', models.FloatField()),
                ('choice_3_percent', models.FloatField()),
                ('quiz_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='papyri.Quiz')),
            ],
        ),
    ]
