# Generated by Django 2.2.7 on 2019-11-24 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('papyri', '0003_auto_20191120_1747'),
        ('papyri', '0006_auto_20191123_0027'),
        ('papyri', '0002_auto_20191124_0853'),
    ]

    operations = [
    ]
