# Generated by Django 2.2.7 on 2019-11-24 09:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('papyri', '0007_merge_20191124_0856'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='teacher_id',
        ),
        migrations.AddField(
            model_name='quiz',
            name='class_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='papyri.ClassInfo'),
            preserve_default=False,
        ),
    ]
