# Generated by Django 2.2.7 on 2019-12-02 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papyri', '0008_auto_20191202_0231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilepic',
            name='pic2',
            field=models.ImageField(blank=True, upload_to='profile_pics<django.db.models.fields.related.ForeignKey>'),
        ),
    ]
