# Generated by Django 2.2.7 on 2019-11-24 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papyri', '0008_auto_20191124_0926'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='quiz',
            name='released',
            field=models.BooleanField(default=False),
        ),
    ]
