# Generated by Django 2.2.7 on 2019-11-24 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papyri', '0009_auto_20191124_0931'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='score',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
