# Generated by Django 2.2.7 on 2019-12-02 02:49

from django.db import migrations, models
import papyri.models


class Migration(migrations.Migration):

    dependencies = [
        ('papyri', '0010_auto_20191202_0238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilepic',
            name='pic1',
            field=models.ImageField(blank=True, upload_to=papyri.models.upload_path_handler),
        ),
        migrations.AlterField(
            model_name='profilepic',
            name='pic3',
            field=models.ImageField(blank=True, upload_to=papyri.models.upload_path_handler),
        ),
        migrations.AlterField(
            model_name='profilepic',
            name='pic4',
            field=models.ImageField(blank=True, upload_to=papyri.models.upload_path_handler),
        ),
        migrations.AlterField(
            model_name='profilepic',
            name='pic5',
            field=models.ImageField(blank=True, upload_to=papyri.models.upload_path_handler),
        ),
    ]
