# Generated by Django 2.2.7 on 2019-11-24 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('papyri', '0004_merge_20191122_0237'),
        ('papyri', '0011_auto_20191124_1025'),
    ]

    operations = [
    ]
