# Generated by Django 2.2.7 on 2019-11-24 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papyri', '0012_merge_20191124_1122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='score',
            field=models.PositiveIntegerField(),
        ),
    ]
