# Generated by Django 2.2.7 on 2019-11-24 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papyri', '0013_auto_20191124_1124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='score',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
